export const Offises = new Map()
Offises.set('Saint-Petersburg', 'Санкт-Петербург')
Offises.set('Minsk', 'Минск')
Offises.set('Yerevan', 'Ереван')
Offises.set('Global', 'Global')
Offises.set('Bytex', 'Bytex')

export const Currencyes = new Map()
Currencyes.set('BYN', 'Белорусский рубль BYN')
Currencyes.set('AMD', 'Армянский драм ֏')
Currencyes.set('USD', 'Доллар США $')
Currencyes.set('RUB', 'Российский рубль ₽')

export const CurrSymbol = new Map()
CurrSymbol.set('BYN', 'Br.')
CurrSymbol.set('AMD', '֏')
CurrSymbol.set('USD', '$')
CurrSymbol.set('RUB', '₽')
CurrSymbol.set('Белорусский рубль BYN', 'Br.')
CurrSymbol.set('Армянский драм ֏', '֏')
CurrSymbol.set('Доллар США $', '$')
CurrSymbol.set('Российский рубль ₽', '₽')
